/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Announcement as PrismaAnnouncement } from "@prisma/client";

export class AnnouncementServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AnnouncementCountArgs, "select">
  ): Promise<number> {
    return this.prisma.announcement.count(args);
  }

  async announcements<T extends Prisma.AnnouncementFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnouncementFindManyArgs>
  ): Promise<PrismaAnnouncement[]> {
    return this.prisma.announcement.findMany<Prisma.AnnouncementFindManyArgs>(
      args
    );
  }
  async announcement<T extends Prisma.AnnouncementFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnouncementFindUniqueArgs>
  ): Promise<PrismaAnnouncement | null> {
    return this.prisma.announcement.findUnique(args);
  }
  async createAnnouncement<T extends Prisma.AnnouncementCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnouncementCreateArgs>
  ): Promise<PrismaAnnouncement> {
    return this.prisma.announcement.create<T>(args);
  }
  async updateAnnouncement<T extends Prisma.AnnouncementUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnouncementUpdateArgs>
  ): Promise<PrismaAnnouncement> {
    return this.prisma.announcement.update<T>(args);
  }
  async deleteAnnouncement<T extends Prisma.AnnouncementDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AnnouncementDeleteArgs>
  ): Promise<PrismaAnnouncement> {
    return this.prisma.announcement.delete(args);
  }
}
