/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Competition } from "./Competition";
import { CompetitionCountArgs } from "./CompetitionCountArgs";
import { CompetitionFindManyArgs } from "./CompetitionFindManyArgs";
import { CompetitionFindUniqueArgs } from "./CompetitionFindUniqueArgs";
import { DeleteCompetitionArgs } from "./DeleteCompetitionArgs";
import { CompetitionService } from "../competition.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Competition)
export class CompetitionResolverBase {
  constructor(
    protected readonly service: CompetitionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "read",
    possession: "any",
  })
  async _competitionsMeta(
    @graphql.Args() args: CompetitionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Competition])
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "read",
    possession: "any",
  })
  async competitions(
    @graphql.Args() args: CompetitionFindManyArgs
  ): Promise<Competition[]> {
    return this.service.competitions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Competition, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "read",
    possession: "own",
  })
  async competition(
    @graphql.Args() args: CompetitionFindUniqueArgs
  ): Promise<Competition | null> {
    const result = await this.service.competition(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Competition)
  @nestAccessControl.UseRoles({
    resource: "Competition",
    action: "delete",
    possession: "any",
  })
  async deleteCompetition(
    @graphql.Args() args: DeleteCompetitionArgs
  ): Promise<Competition | null> {
    try {
      return await this.service.deleteCompetition(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
